/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Mahmoud Elgendy
 *
 * Created on September 18, 2023, 10:30 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE  1
#define INTERRUPT_FEATURE_DISABLE 0

#define EXTERNAL_INTERRUPT_INT_FEATURE_ENABLE       INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_ONCHANGE_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE 

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

